---
name: Build PyInstaller
on:
  push:
  schedule:
    - cron: '15 16 * * 3,6'

jobs:
  build:
    name: Build package
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: pyinstaller/pyinstaller
          ref: v6.12.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Build 64-bit bootloader
        run: |
          cd bootloader
          python waf distclean all --target-arch=64bit

      - name: Build 32-bit bootloader
        run: |
          cd bootloader
          python waf distclean all --target-arch=32bit

      - name: Build packages
        run: |
          python -m pip install wheel
          python setup.py sdist bdist_wheel

      - name: Archive packages
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish package
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download archived package
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Find dist files
        id: files
        run: echo "::set-output name=FILES::$(find -type f -printf '%p ')"

      - name: Publish snapshot package
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: snapshot
          body: "Snapshot build"
          files: ${{ steps.files.outputs.FILES }}
          allow_override: true
          gzip: false
